Sprint 1
sstark21/middle.messenger.praktikum.yandex pull request #2
Opened 2021-07-11 19:50 UTC by sstark21

Исправил по максимуму, комментарии оставил к прошлому ревью

2021-07-11 20:01 UTC, sstark21 commented
я немного затупил, и смержил сам прошлую версию, эту не мержу до проверки!

2021-07-12 11:14 UTC, nickchamel requested changes
Отлично, чище и аккуратней, но осталась проблемка с модульностью. По заданию шаблоны должны лежать в отдельных файлах, поэтому стоит реорганизовать структуру немного + есть комментарии по неймингу. У тебя вроде последняя попытка из-за того что репозиторий был приватный изначально, я работу пока не возвращаю тогда, доделай пожалуйста и маякни здесь, осталось немного

2021-07-12 11:14 UTC, nickchamel commented on src/templates/404.js
> +const error404Content = `
Я в том комментарии тебе за нейминг говорил, а не за hbs) Конечно ты можешь использовать строки, это я так в общем. А тут проблема с неймингом осталась.
это как раз таки не Content, а темплейт, потому что здесь присутсвуют пропсы, то есть это не html, это шаблон. `error404Template`.
Далее на 18 строке `Hbs.compile(error404Template)` возвращает функцию компиляции, а не темплейт, то есть например `compileError404Template`
А уже `compileError404Template(context)` вернет content или html или т.п.
Сатарйся называть вещи своими именами, иначе код сложно читать и поддерживать.
Второй момент - все шаблоны по заданию нужно хранить в отдельном файле. Это опять же к вопросу о модульности. У тебя в папке src/templates лежат js-ники, темлпейты это грубо говоря html с дополнениями,  а не js код. Что из себя представляет модуль - это папка в нем может быть index.js (входная точка модуля), component.js (содержимое этого файла, без шаблона), template.js (шаблон), styles.scss (уникальные стили для этого модуля) Эти стили и шаблон импортятся здесь, сборщик при импорте стилей автоматом добавит их к итоговому css-бандлу. Таким образом получится что у тебя на каждой странице будет только необходимый для нее js-код и css.

2021-07-12 11:14 UTC, nickchamel commented on src/templates/messenger.js
> +console.log("MESSENGER", messengerResult);
логи можно убрать

2021-07-12 11:14 UTC, nickchamel commented on src/templates/404.js
> +    button_link: "/messenger.html",
А это не `reloadButtonLink `, а например `reloadButtonLinkContext`

2021-07-12 21:29 UTC, sstark21 commented on src/templates/messenger.js
> +console.log("MESSENGER", messengerResult);
убрал

2021-07-12 21:29 UTC, sstark21 commented on src/templates/404.js
> +    button_link: "/messenger.html",
поправил

2021-07-12 21:29 UTC, sstark21 commented on app.js
> +app.use(express.static('src/styles'))
надеюсь речь про это `app.use(express.static('src/styles'))`
у меня чет не работало и я добавил это для теста и забыл убрать

2021-07-12 21:42 UTC, sstark21 commented on src/templates/404.js
> +const error404Content = `
-Поправил нейминг везде.
-Вынес в модули шаблоны и логику
-Добавил уникальные scss в js файлах

Мне не очень нравится название самой папки templates, потому что это не прям только шаблоны, может что-то посоветуешь.

ну а так, вроде все))))

2021-07-12 21:48 UTC, sstark21 commented
@nickchamel запушил новый коммит 
big refactor + renaming

2021-07-13 11:26 UTC, nickchamel requested changes
> Мне не очень нравится название самой папки templates, потому что это не прям только шаблоны, может что-то посоветуешь.

могу конечно) `components`
обычно есть src/pages и src/components
И там и там папки с модулями. Каждый модуль это index.js, имяМодуля.js, стилиМодуля.scss/any, шаблонМодуля.any
Ты можешь в src/pages сделать папки для страниц и к ихним html-файлам положить ихние js-ники и стили.
Остальное оставить в src/components и для того, что у тебя сейчас лежит в templates/components можно тоже сделать отдельные папки, в дальнейшем эти компоненты могут усложняться и т.п.
Плюс если ты так сделаешь то тебе не придется делать так:
```
import { authTemplate } from "./template";
import { inputFieldTemplate } from "../components/inputFieldTemplate";
import { bigDarkButtonTemplate } from "../components/bigDarkButtonTemplate";

const compileAuthTemplate = Hbs.compile(authTemplate);
const compileAuthInputsTemplate = Hbs.compile(inputFieldTemplate);
const compileAuthSignUpButtonTemplate = Hbs.compile(bigDarkButtonTemplate);
```
ты можешь экспортить из js-файлов компонентов Hbs.compile(authTemplate);
и тогда тебе не придется везде где ты используешь какой-либо компонент делать вызов Hbs.compile(...
```
import compileAuthTemplate from "./template";
import compileAuthInputsTemplate from "../components/inputFieldTemplate";
import compileAuthSignUpButtonTemplate from "../components/bigDarkButtonTemplate";
```

2021-07-14 09:44 UTC, sstark21 commented
@nickchamel все сделал как ты сказал, пришлось изрядно попотеть с новой сборкой и express. но все работает, жду оценку!))

2021-07-14 11:07 UTC, nickchamel approved these changes
Отлично! Молодец, вообще `parcel build src/**/*.html && npm run express` достаточно для работы вроде как. В любом случае в 3 спринте будет клиентский роутинг и html-файл останется один, так что там все равно будут переделки в этом плане.
Работу принимаю, удачи в дальнейшем

2021-07-14 11:15 UTC, merged

2021-07-14 11:15 UTC, sstark21 commented
@nickchamel спасибо за правки и опыт!))